coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        branches:
          - main
        ignore:
          - "pkg/commmands/*" # Cobra commands
