name: Build and push a new adhoc release

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Branch to build from"
        required: true
        default: "main"

permissions:
  contents: write

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.events.inputs.build_branch }}
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: " 1.21.x"
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

  docker:
    name: Build container and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.events.inputs.build_branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Get Tags for Image
      #   id: metadata
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ministryofjustice/cloud-platform-cli
      #     tags: |
      #       type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.events.inputs.build_branch }}
          build-args: CLOUD_PLATFORM_CLI_VERSION=${{ github.events.inputs.build_branch }}
