name: Add dependencies to Cloud Platform project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  add-dependabot-to-projcet:
    uses: ministryofjustice/cloud-platform-github-workflows/.github/worfkflows/dependencies-project.yml
